name: Run flask project
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Dockere Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-remove:latest
  pull-run:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Pull the self created image from dockerhub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/flask-remove

      - name: Run the pulled image
        run: docker run -e FLASK_DEBUG=value ${{ secrets.DOCKERHUB_USERNAME }}/flask-remove:latest
        env:
          FLASK_DEBUG: False

